[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "my_numerical_package"
version = "0.1.0"
description = "A brief description of my project."

dependencies = [
    "numpy>=2.1.0"
]